# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-13 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=140)),
                ('birthday', models.DateField(max_length=2000)),
                ('eligible', models.CharField(max_length=2000)),
                ('random_number', models.IntegerField()),
                ('bizz_fuzz', models.CharField(max_length=140)),
            ],
        ),
    ]
