# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0003_auto_20170213_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='birthday',
            field=models.CharField(max_length=2000),
        ),
    ]
